/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef mis_CONSTANTS_H
#define mis_CONSTANTS_H

#include "mis_types.h"



class misConstants {
 public:
  misConstants();

};

extern const misConstants g_mis_constants;



#endif
