/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "mis_constants.h"



const misConstants g_mis_constants;

misConstants::misConstants() {
}



