// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "MISInterface.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class MISInterfaceHandler : virtual public MISInterfaceIf {
 public:
  MISInterfaceHandler() {
    // Your initialization goes here
  }

  void check(MISResponse& _return, const MISRequest& request) {
    // Your implementation goes here
    printf("check\n");
  }

  void add2Q(const MISRequest& request, const std::string& reason) {
    // Your implementation goes here
    printf("add2Q\n");
  }

  int8_t ping() {
    // Your implementation goes here
    printf("ping\n");
  }

  void reload() {
    // Your implementation goes here
    printf("reload\n");
  }

  void quit() {
    // Your implementation goes here
    printf("quit\n");
  }

  int32_t getCurMsgNum() {
    // Your implementation goes here
    printf("getCurMsgNum\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<MISInterfaceHandler> handler(new MISInterfaceHandler());
  shared_ptr<TProcessor> processor(new MISInterfaceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

